# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b63a294f7ee83269dacca4406d425205799264fdc99b0d87612162086697e62317435980b3a6f4fa441baa839612ebb20079323e46420e4b1bcb6ec11f86de5

test:
  secret_key_base: 6997d8961ff9562697634bc130f75ce8d91895eb7e4c84297b456c7ef3b55c0163f4d36b713a3fc6bdf3c7f7ee81011e9a46c078194ef88cebb2ec446e381b3c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
